# Generated by Django 5.2 on 2025-04-27 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_modules', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='content_type',
            field=models.CharField(choices=[('blog', 'Blog Post'), ('video', 'Video'), ('pdf', 'PDF')], default='blog', max_length=20),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_modules', to='blog.document'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_modules', to='blog.video'),
        ),
    ]
