# Generated by Django 5.2 on 2025-04-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_coursemodule_blog_post_coursemodule_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='course_documents/'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in KB', null=True),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='text_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
