# Generated by Django 5.2 on 2025-04-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_coursemodule_document_file_coursemodule_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='blog_post',
        ),
        migrations.RemoveField(
            model_name='coursemodule',
            name='document',
        ),
        migrations.RemoveField(
            model_name='coursemodule',
            name='video',
        ),
    ]
